In [6]:
!git clone https://github.com/NLP-Projects/Vietnamese-Sentiment-Analysis.git

Cloning into 'Vietnamese-Sentiment-Analysis'...
remote: Enumerating objects: 56, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 247 (delta 31), reused 0 (delta 0), pack-reused 191
Receiving objects: 100% (247/247), 3.65 MiB | 6.55 MiB/s, done.
Resolving deltas: 100% (136/136), done.


In [63]:
import pandas as pd
import numpy as np
import random

In [64]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [65]:
string.punctuation.replace('_', '')
punctuation = string.punctuation.replace('_', '')
def remove_punctuation(text):
  no_punct = [words for words in text if words not in punctuation]
  words_no_punct=''.join(no_punct)
  return words_no_punct

In [66]:
MAX_LENGTH = 10
padding = [0 for i in range(150)]

In [67]:
dicts = {}
i = 0
with open("/content/W2V_150.txt") as f:
    for lines in f:
        i += 1
        if i >= 3:
            line = lines.split()
            key = line[0]
            line.pop(0)
            val = line
            dicts[str(key)] = val
            for i in range(0, len(val)):
                val[i] = float(val[i])

In [68]:
def get_proper_input_from_file(path):
  proper_input = []
  with open(path) as f:
    for line in f:
      if line.rstrip():
        sentence = []
        
        line = line.replace('\xa0', '')
        line = line.replace('\n', '')
        line = line.replace('\ufeff', '')
        line = line.lower()
        line = remove_punctuation(line)
        words = line.split()
        n_words = len(words)
        if n_words >= MAX_LENGTH:
          sentence.extend([padding if dicts.get(words[i]) is None else dicts.get(words[i]) for i in range(MAX_LENGTH)])
        else:
          sentence.extend([padding if dicts.get(word) is None else dicts.get(word) for word in words])
          sentence.extend([padding for i in range(MAX_LENGTH - n_words)])
        proper_input.append(sentence)
  return proper_input

In [69]:
X_train_negative = get_proper_input_from_file('/content/Vietnamese-Sentiment-Analysis/train_negative_tokenized.txt')
X_train_neutral = get_proper_input_from_file('/content/Vietnamese-Sentiment-Analysis/train_neutral_tokenized.txt')
X_train_positive = get_proper_input_from_file('/content/Vietnamese-Sentiment-Analysis/train_positive_tokenized.txt')

In [70]:
X_train = []
X_train += X_train_negative + X_train_neutral + X_train_positive

In [71]:
# y_train_negative = np.zeros((len(X_train_negative), 1)).tolist() #0
# y_train_neutral = np.ones((len(X_train_neutral), 1)).tolist() #1
# y_train_positive = np.full((len(X_train_positive), 1), 2).tolist() #2
y_train = []

y_train_negative = [0 for i in range(len(X_train_negative))]
y_train_neutral = [1 for i in range(len(X_train_neutral))]
y_train_positive = [2 for i in range(len(X_train_positive))]

y_train += y_train_negative + y_train_neutral + y_train_positive

In [72]:
def average_list(lst):
    return sum(lst) / len(lst) 

# X_train[0][0]

Final_X_train = []

for x_train in X_train:
  final_X_train = [average_list(word) for word in x_train]
  Final_X_train.append(final_X_train)

Final_y_train = []

print(y_train)


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [73]:
import torch

X_tensor = torch.FloatTensor(Final_X_train)

y_tensor = torch.IntTensor(y_train)


temp_tensor = torch.FloatTensor(X_train)

temp_tensor_y = torch.LongTensor(y_train)

print("type X_tensor", len(X_tensor))
print("type x_tensor", len(y_tensor))
print(len(temp_tensor))

type X_tensor 5100
type x_tensor 5100
5100


In [88]:
import torch 
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms


# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Hyper-parameters
sequence_length = MAX_LENGTH
input_size = 150
hidden_size = 128
num_layers = 2
num_classes = 3
batch_size = 100
num_epochs = 2
learning_rate = 0.01



# Recurrent neural network (many-to-one)
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super(RNN, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, num_classes)
    
    def forward(self, x):
        # Set initial hidden and cell states 
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device) 
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)
        
        # Forward propagate LSTM
        out, _ = self.lstm(x, (h0, c0))  # out: tensor of shape (batch_size, seq_length, hidden_size)
        
        # Decode the hidden state of the last time stepn
        out = self.fc(out[:, -1, :])
        return out

model = RNN(input_size, hidden_size, num_layers, num_classes).to(device)


In [89]:
# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# print(X_train[0])

# Train the model
total_step = len(temp_tensor)
for epoch in range(180):
    # for i, (sentences, labels) in enumerate(zip(temp_tensor, temp_tensor_y)):
    #     # sentences = sentences.reshape(-1, sequence_length, input_size).to(device)
    #     # labels = labels.to(device)
        
    #     # Forward pass
        outputs = model(temp_tensor)
        loss = criterion(outputs, temp_tensor_y)
        
        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        print(epoch, loss.item())
        
        # if (i+1) % 100 == 0:
        #     print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}' 
        #            .format(epoch+1, num_epochs, i+1, total_step, loss.item()))

0 1.098891258239746
1 1.0718889236450195
2 0.9654040336608887
3 1.4880963563919067
4 0.9944305419921875
5 1.0663210153579712
6 1.0023225545883179
7 0.980668842792511
8 0.9920761585235596
9 0.979638934135437
10 0.9583986401557922
11 0.936053454875946
12 0.9107332825660706
13 0.8920945525169373
14 0.8893408179283142
15 0.8748292922973633
16 0.8529558181762695
17 0.8261096477508545
18 0.8034732341766357
19 0.7908490300178528
20 0.7699511051177979
21 0.7553325295448303
22 0.7388906478881836
23 0.7123042345046997
24 0.6907649040222168
25 0.6686773300170898
26 0.6438372135162354
27 0.6162672638893127
28 0.5851864218711853
29 0.5597655177116394
30 0.5553593039512634
31 0.7501255869865417
32 0.4954994320869446
33 0.811011016368866
34 0.5546544790267944
35 0.7093281745910645
36 0.7366707921028137
37 0.6910688281059265
38 0.6342257261276245
39 0.5882550477981567
40 0.5554245114326477
41 0.5337457060813904
42 0.5176045298576355
43 0.4898260235786438
44 0.4495486617088318
45 0.4184173047542572
46 

In [90]:
def get_label_token(label):
  if label == "POS":
    return 2
  if label == "NEU":
    return 1
  if label == "NEG":
    return 0

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=200, random_state=0)
clf.fit(Final_X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=200, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [91]:
cau = []
sentence_test = []
label_test = []

with open("/content/Vietnamese-Sentiment-Analysis/test_tokenized_ANS.txt") as f:
  i = 1
  for line in f:
    if i%2==0:
      label = line.split('\n')[0]
      label_test.append(get_label_token(label))
    else:
      cau.append(line)
      sentence = []
      line = line.replace('\xa0', '')
      line = line.replace('\n', '')
      line = line.replace('\ufeff', '')
      line = remove_punctuation(line)
      line = line.lower()
      words = line.split()
      n_words = len(words)
      if n_words >= MAX_LENGTH:
        sentence.extend([padding if dicts.get(words[i]) is None else dicts.get(words[i]) for i in range(MAX_LENGTH)])
      else:
        sentence.extend([padding if dicts.get(word) is None else dicts.get(word) for word in words])
        sentence.extend([padding for i in range(MAX_LENGTH - n_words)])
      sentence_test.append(sentence)
    i += 1
    # line = remove_punctuation(line)
    # words = line.split()
    # n_words = len(words)
    # if n_words >= MAX_LENGTH:
    #   sentence.extend([padding if dicts.get(words[i]) is None else dicts.get(words[i]) for i in range(MAX_LENGTH)])
    # else:
    #   sentence.extend([padding if dicts.get(word) is None else dicts.get(word) for word in words])
    #   sentence.extend([padding for i in range(MAX_LENGTH - n_words)])
    # proper_input.append(sentence)




In [92]:
test_sentence = torch.FloatTensor(sentence_test)

test_label = torch.LongTensor(label_test)

In [93]:
# Test the model
model.eval()
with torch.no_grad():
    correct = 0
    total = 0
    outputs = model(test_sentence)
    _, predicted = torch.max(outputs.data, 1)
    total += test_label.size(0)
    # correct += (predicted == labels).sum().item()

    # print('Test Accuracy of the model on the 10000 test images: {} %'.format(100 * correct / total)) 

In [94]:
from sklearn.metrics import accuracy_score
accuracy_score(test_label, predicted)

0.5838095238095238

In [86]:
predicted

tensor([1, 2, 1,  ..., 0, 1, 1])

In [87]:
test_label

tensor([2, 0, 1,  ..., 1, 0, 2])

In [95]:
torch.max(outputs.data, 1)

torch.return_types.max(values=tensor([1.5087, 6.4793, 6.5002,  ..., 5.6810, 6.7190, 7.7162]), indices=tensor([0, 2, 1,  ..., 0, 1, 2]))

In [ ]:
# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# print(X_train[0])

# Train the model
total_step = len(temp_tensor)
for epoch in range(100):
    # for i, (sentences, labels) in enumerate(zip(temp_tensor, temp_tensor_y)):
    #     # sentences = sentences.reshape(-1, sequence_length, input_size).to(device)
    #     # labels = labels.to(device)
        
    #     # Forward pass
        outputs = model(temp_tensor)
        loss = criterion(outputs, temp_tensor_y)
        
        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        print(loss.item())
        
        # if (i+1) % 100 == 0:
        #     print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}' 
        #            .format(epoch+1, num_epochs, i+1, total_step, loss.item()))

2.346555471420288


KeyboardInterrupt: ignored

In [ ]:
# Train the model
total_step = len(X_tensor)
for epoch in range(num_epochs):
  X_tensor, y_tensor
  outputs = model(X_tensor)
  loss = criterion(outputs, y_tensor)

  # print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}' 
  #     .format(epoch+1, num_epochs, i+1, total_step, loss.item()))
  
  print(loss)
  # for i, (, b) in enumerate(zip([1,2,3], [4,5,6])):
  #   print(f, b)
  #   for i, (images, labels) in enumerate(X_tensor):
  #       images = images.reshape(-1, sequence_length, input_size).to(device)
  #       labels = labels.to(device)
        
  #       # Forward pass
  #       outputs = model(images)
  #       loss = criterion(outputs, labels)
        
  #       # Backward and optimize
  #       optimizer.zero_grad()
  #       loss.backward()
  #       optimizer.step()
        
  #       if (i+1) % 100 == 0:
  #           print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}' 
  #                  .format(epoch+1, num_epochs, i+1, total_step, loss.item()))

# Test the model
# model.eval()
# with torch.no_grad():
#     correct = 0
#     total = 0
#     for images, labels in test_loader:
#         images = images.reshape(-1, sequence_length, input_size).to(device)
#         labels = labels.to(device)
#         outputs = model(images)
#         _, predicted = torch.max(outputs.data, 1)
#         total += labels.size(0)
#         correct += (predicted == labels).sum().item()

#     print('Test Accuracy of the model on the 10000 test images: {} %'.format(100 * correct / total)) 

# # Save the model checkpoint
# torch.save(model.state_dict(), 'model.ckpt')

RuntimeError: ignored

In [ ]:
y_pred = model.predict(sentence_test)

ModuleAttributeError: ignored

In [ ]:
for i, (f, b) in enumerate(zip([1,2,3], [4,5,6])):
    print(f, b)

1 4
2 5
3 6


In [ ]:
# MNIST dataset
train_dataset = torchvision.datasets.MNIST(root='../../data/',
                                           train=True, 
                                           transform=transforms.ToTensor(),
                                           download=True)

test_dataset = torchvision.datasets.MNIST(root='../../data/',
                                          train=False, 
                                          transform=transforms.ToTensor())

# Data loader
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                           batch_size=batch_size, 
                                           shuffle=True)

test_loader = torch.utils.data.DataLoader(dataset=test_dataset,
                                          batch_size=batch_size, 
                                          shuffle=False)

In [ ]:
    # for i, (images, labels) in enumerate(train_loader):
    #   print(type(labels[0]))
    #     # images = images.reshape(-1, sequence_length, input_size).to(device)
    #     # labels = labels.to(device)

In [ ]:
import torch 
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms


# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Hyper-parameters
sequence_length = 28
input_size = 28
hidden_size = 128
num_layers = 2
num_classes = 10
batch_size = 100
num_epochs = 2
learning_rate = 0.01



# Recurrent neural network (many-to-one)
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super(RNN, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, num_classes)
    
    def forward(self, x):
        # Set initial hidden and cell states 
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device) 
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)
        
        # Forward propagate LSTM
        out, _ = self.lstm(x, (h0, c0))  # out: tensor of shape (batch_size, seq_length, hidden_size)
        
        # Decode the hidden state of the last time step
        out = self.fc(out[:, -1, :])
        return out

model = RNN(input_size, hidden_size, num_layers, num_classes).to(device)


# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# Train the model
total_step = len(train_loader)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        images = images.reshape(-1, sequence_length, input_size).to(device)
        labels = labels.to(device)
        
        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)
        
        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}' 
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))

# Test the model
model.eval()
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in test_loader:
        images = images.reshape(-1, sequence_length, input_size).to(device)
        labels = labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print('Test Accuracy of the model on the 10000 test images: {} %'.format(100 * correct / total)) 

# Save the model checkpoint
torch.save(model.state_dict(), 'model.ckpt')

Extracting ../../data/MNIST/raw/train-images-idx3-ubyte.gz to ../../data/MNIST/raw


Extracting ../../data/MNIST/raw/train-labels-idx1-ubyte.gz to ../../data/MNIST/raw



Extracting ../../data/MNIST/raw/t10k-images-idx3-ubyte.gz to ../../data/MNIST/raw


Extracting ../../data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ../../data/MNIST/raw
Processing...
Done!


/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py:480: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:141.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)



Epoch [1/2], Step [100/600], Loss: 0.3285


KeyboardInterrupt: ignored

In [ ]:
import torch 
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms


# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Hyper-parameters
sequence_length = 20
input_size = 1700
hidden_size = 128
num_layers = 2
num_classes = 10
batch_size = 100
num_epochs = 2
learning_rate = 0.01

class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super(RNN, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)  
        self.fc = nn.Linear(hidden_size, num_classes)
    
    def forward(self, x):
        # Set initial hidden and cell states 
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device) 
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)
        
        # Forward propagate LSTM
        out, _ = self.lstm(x, (h0, c0))  # out: tensor of shape (batch_size, seq_length, hidden_size)
        
        # Decode the hidden state of the last time step
        out = self.fc(out[:, -1, :])
        return out

model = RNN(input_size, hidden_size, num_layers, num_classes).to(device)
# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [ ]:
X_train = np.asarray(X_train)
y_train = np.asarray(y_train)

total_step = len(train_loader)
for epoch in range(num_epochs):
    for i, (sentences, labels) in (X_train, y_train):
        # images = images.reshape(-1, sequence_length, input_size).to(device)
        # labels = labels.to(device)
        sentences
        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)
        
        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}' 
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))

In [ ]:
X_train[0][0] # 1 gia tri da la mot list cua 1 list r

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [ ]:
# for i, (a, b) in enumerate(train_loader):
#   print(b.to(device))

tensor([4, 4, 2, 1, 0, 8, 2, 2, 1, 9, 1, 5, 1, 1, 9, 4, 1, 0, 8, 3, 3, 5, 5, 9,
        2, 1, 5, 7, 7, 8, 3, 7, 8, 9, 4, 3, 4, 8, 4, 2, 6, 1, 9, 7, 8, 2, 6, 0,
        7, 2, 6, 7, 5, 4, 8, 7, 3, 5, 3, 5, 7, 6, 1, 9, 6, 2, 0, 4, 3, 0, 1, 1,
        0, 0, 0, 3, 0, 9, 5, 3, 3, 3, 9, 7, 2, 3, 2, 6, 1, 8, 2, 6, 8, 0, 7, 9,
        6, 6, 4, 9])
tensor([3, 2, 6, 7, 5, 0, 6, 8, 4, 8, 6, 4, 0, 2, 4, 3, 0, 9, 5, 0, 8, 7, 1, 5,
        9, 0, 2, 7, 9, 6, 4, 0, 5, 8, 8, 2, 0, 8, 2, 6, 2, 9, 1, 8, 3, 0, 8, 9,
        3, 9, 4, 2, 7, 1, 7, 4, 5, 1, 6, 6, 7, 5, 4, 9, 2, 4, 0, 5, 9, 2, 0, 4,
        4, 3, 4, 3, 3, 2, 6, 0, 4, 3, 1, 3, 0, 7, 6, 8, 3, 9, 4, 8, 2, 7, 0, 9,
        7, 3, 7, 6])
tensor([3, 2, 8, 3, 3, 2, 2, 3, 3, 5, 0, 6, 6, 3, 8, 2, 0, 7, 0, 4, 0, 3, 5, 4,
        1, 2, 7, 1, 9, 4, 4, 1, 1, 4, 5, 0, 8, 1, 7, 5, 2, 5, 2, 4, 7, 9, 3, 0,
        6, 6, 3, 8, 0, 7, 4, 4, 5, 7, 6, 9, 1, 8, 1, 2, 0, 3, 8, 8, 5, 3, 3, 0,
        2, 9, 7, 7, 0, 0, 9, 4, 0, 7, 2, 9, 1, 3, 0, 3, 0, 0, 8, 6, 2, 3, 6, 2

KeyboardInterrupt: ignored

In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Model
from keras.layers import LSTM, Activation, Dense, Dropout, Input, Embedding
from keras.optimizers import RMSprop
from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
from keras.utils import to_categorical
from keras.callbacks import EarlyStopping
from tensorflow import keras


In [50]:
max_len = 10
max_words = 150
def RNN():
    inputs = Input(name='inputs',shape=[max_len])
    layer = Embedding(max_words,50,input_length=max_len)(inputs)
    layer = LSTM(64)(layer)
    layer = Dense(256,name='FC1')(layer)
    layer = Activation('relu')(layer)
    layer = Dropout(0.5)(layer)
    layer = Dense(1,name='out_layer')(layer)
    layer = Activation('sigmoid')(layer)
    model = Model(inputs=inputs,outputs=layer)
    return model

In [55]:
model = RNN()
model.summary()
opt = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='categorical_crossentropy', optimizer=opt,metrics=['accuracy'])
# model.compile(loss='categorical_crossentropy',optimizer='Adam')

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
inputs (InputLayer)          [(None, 10)]              0         
_________________________________________________________________
embedding_6 (Embedding)      (None, 10, 50)            7500      
_________________________________________________________________
lstm_6 (LSTM)                (None, 64)                29440     
_________________________________________________________________
FC1 (Dense)                  (None, 256)               16640     
_________________________________________________________________
activation_4 (Activation)    (None, 256)               0         
_________________________________________________________________
dropout_6 (Dropout)          (None, 256)               0         
_________________________________________________________________
out_layer (Dense)            (None, 1)                 257 

In [56]:
model.fit(Xtrain,ytrain,batch_size=128,epochs=200,
          validation_split=0.2,callbacks=[EarlyStopping(monitor='val_loss',min_delta=0.0001)])

Epoch 1/200
32/32 [==============================] - 3s 37ms/step - loss: 0.0000e+00 - accuracy: 0.4219 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 2/200
32/32 [==============================] - 1s 16ms/step - loss: 0.0000e+00 - accuracy: 0.4159 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00


In [53]:
Xtrain = np.asarray(Final_X_train)
ytrain = np.asarray(y_train)

In [ ]:
ytrain.shape

(5100,)

In [ ]:
Xtrain.shape

(5100, 10)

In [ ]:
Xtrain[0]

array([ 0.10011094,  0.00679974, -0.04322006,  0.        ,  0.04425758,
       -0.00592822, -0.12355259, -0.04418195,  0.00251656,  0.06973758,
        0.12619839, -0.01220402,  0.06705025, -0.10393883,  0.0303264 ,
        0.03785477, -0.08024879, -0.07393216,  0.11420554,  0.01814113])

In [ ]:
ytrain[0]

0